dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: molecule-centos
    image: centos:centos7.9.2009
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
provisioner:
  name: ansible
  inventory:
    host_vars:
      molecule-centos:
        titre: "test"
        color: blue
        text: "test"
