dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: molecule-centos
    image: centos:centos7.9.2009
    dockerfile: Dockerfile.j2
provisioner:
  name: ansible
  inventory:
    host_vars:
      molecule-centos:
        titre: "test"
        color: blue
        text: "test"