---
# tasks file for lb-nginx

- name: Check that you can connect (GET) to a page and it returns a status 200
  ansible.builtin.uri:
    url: http://www.google.com

- name: Add epel-release repo
  yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
- name: Install systemd
  yum: 
    name: systemd
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: config files
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: start nginx
  service:
    name: nginx
    state: started
