---
# tasks file for server-nginx
- name: Check that you can connect (GET) to a page and it returns a status 200
  ansible.builtin.uri:
    url: http://www.google.com

- name: Add epel-release repo
  yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
- name: Install systemd
  yum: 
    name: systemd
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: config files
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: create folder
  file:
    path: /home/foo/static-site/
    state: directory

- name: source copy
  template:
    src: "{{ item.src }}"
    dest: "/home/foo/static-site/{{ item.dest }}"
  vars:
    text: "{{hostvars[inventory_hostname]['text'] }}"
    color: "{{hostvars[inventory_hostname]['color'] }}"
  loop:
    - { src: index.html.j2, dest: index.html}
    - { src: style.css.j2, dest: style.css}

- name: restart nginx
  service:
    name: nginx
    state: started